library(readr)
n <- read_csv("C:/datascience/thesis/manipulateddata/graphs/cross-validation.ame")
n$`K- fold Cross Validation` <- as.numeric(n$`K- fold Cross Validation`)
n$`FE(covar&E.D)-Classifier(ANN)` <- as.numeric(n$`FE(covar&E.D)-Classifier(ANN)`)
n$`FE(covar)-Classifier(ANN)` <- as.numeric(n$`FE(covar)-Classifier(ANN)`)
x <- c(1:10)
plot(n$`FE(svd)-Classifier(ANN) Including Time variable`, type = "o", col = "blue",ylim = c(95,100),axes = F, ann = F, lwd = 2)
axis(1, at=1:10, lab = n$`K- fold Cross Validation`)
axis(2,95:100)
box()
lines(n$`FE(svd)-Classifier(ANN) without Including Time variable`, type="o", pch=22, lty=1, col="red", lwd = 2)
title(xlab= "K-fold Cross Validation", col.lab="black")
title(ylab= "Accuracy", col.lab="black")
title(main="Accuracy of ANN Classifier model and S.V.D as FE Technique based on Time Variable ", col.main="black", font.main=2)
legend("topleft", names(n[,5:6]),pch = c(1,22), col = c("blue","red"), lty = 1,cex = 1.3,lwd = 2)