library(readr)
n <- read_csv("C:/datascience/thesis/manipulateddata/graphs/cross-validation.ame")
n$`K- fold Cross Validation` <- as.numeric(n$`K- fold Cross Validation`)
n$`FE(covar&E.D)-Classifier(ANN)` <- as.numeric(n$`FE(covar&E.D)-Classifier(ANN)`)
n$`FE(covar)-Classifier(ANN)` <- as.numeric(n$`FE(covar)-Classifier(ANN)`)
x <- c(1:10)
plot(n$`FE(covar&E.D)-Classifier(ANN)`, type = "o", col = "blue",ylim = c(97,100),axes = F, ann = F, lwd = 2)
                                                                                  
axis(1, at=1:10, lab = n$`K- fold Cross Validation`)
axis(2,97:100)
box()
lines(n$`FE(covar)-Classifier(ANN)`, type="o", pch=22, lty=1, col="red", lwd = 2)
lines(n$`FE(E.D)-Classifier(ANN)`, type="o", pch=23, lty=1, col="forest green", lwd = 2)
title(xlab= "K-fold Cross Validation", col.lab="black")
title(ylab= "Accuracy", col.lab="black")
title(main="Accuracy of ANN Classifier model for different Feature extraction Technique", col.main="black", font.main=2)
legend("bottomright", names(n[,2:4]),pch = c(1,22,23), col = c("blue","red","forest green"), lty = 1,cex = 1.3,lwd = 2)