library(readr)
m <- read.csv("C:/datascience/thesis/manipulateddata/maniplateddata/194/CAN_1/KDL1-RT23_A05_CAN1_000006.ame", header = T," ")
boxplot(m[,-5],las = 2, names = c("Current","Force","Distance","Voltage"), main = "Boxplot of Variables in MTS")
summary(m[,-5])
# par(mfrow = c(2,2))
boxplot(m$I30.A., main = "Boxplot of Sensor signals in MTS", xlab = "Current")
boxplot(m$Force.N., xlab = "Force")
boxplot(m$Distance.mm., xlab = "Distance")
boxplot(m$U30.v., xlab = "Voltage")
