library(readr)
m <- read.csv("C:/datascience/thesis/manipulateddata/maniplateddata/194/CAN_1/KDL1-RT23_A05_CAN1_000072.ame",header = T," ")
m1 <- read.csv("C:/datascience/thesis/manipulateddata/maniplateddata/194/CAN_1/KDL1-RT23_A05_CAN1_000124.ame",header = T," ")
m2 <- read.csv("C:/datascience/thesis/manipulateddata/maniplateddata/194/CAN_1/KDL1-RT23_A05_CAN1_000566.ame",header = T," ")
m3 <- read.csv("C:/datascience/thesis/manipulateddata/maniplateddata/194/CAN_1/KDL1-RT23_A05_CAN1_000011.ame",header = T," ")
par(mfrow = c(2,2), cex.lab = 1.7)
boxplot(m$Distance.mm., xlab = "Tooth to Tooth")
boxplot(m1$Distance.mm., xlab = "Bsr Too Long")
boxplot(m2$Distance.mm., xlab = "Tooth to Tooth and BSR Too Long")
boxplot(m3$Distance.mm., xlab = "Ideal")
