library(readr)
n <- read_csv("C:/datascience/thesis/manipulateddata/graphs/roc.ame")
plot(n$fpr1,n$tpr1,lwd = 4, lty = 2, type = "o",col = "blue", xlab = "False positive rate", ylab = "True positive rate")
lines(n$fpr2,n$tpr2, lwd = 4, lty =2,type = "o",col ="red")
lines(n$fpr3,n$tpr3, lwd = 4, lty = 2, type = "o", col = "black")
lines(n$fpr4,n$tpr4, lwd = 4, lty = 2, type = "o", col = "forest green")
lines(n$fpr5,n$tpr5, lwd = 4, lty = 2, type = "o", col = 8)
lines(n$fpr6,n$tpr6, lwd = 4, lty = 2, type = "o", col = 6)
lines(n$fpr7,n$tpr7, lwd = 4, lty = 2, type = "o", col = "gold")
title(main = "Reciever operating Characteristic Curves",col.main="black", font.main=2)
legend("bottomright", c("FE(covar&E.D)-Classifier(ANN)","FE(covar)-Classifier(ANN)","FE(E.D)-Classifier(ANN)","FE(svd)-Classifier(ANN) Including Time variable","FE(svd)-Classifier(ANN) without Including Time variable","FE(svd)-Classifier(KNN) Including Time variable","FE(svd)-Classifier (KNN)
without Including Time variable"), col = c("blue","red","black","forest green",8,6,"gold"), lty = 2,cex = 1,lwd = 2)
